### ISSUE TITLE
Details of generating sfc data for the fractional landmask

### ISSUE THREAD

**Issue by shansun6** [ufs-community/UFS_UTILS#145]
This issue is complementary to the current "chgres" by adding 2 new variables in sfc_data, desirable for the fractional landmask to have a SST and roughness length over land and water, separately. 

Here are the details of generating sfc data for the fractional landmask:

(1) Using “land_frac” in the oro_data to define slmsk; Points with 0 < land_frac < 1 indicates there are some land and some water at this grid point.

(1a) slmsk=ceiling(land_frac) is to take fractional grids as land points. With this slmsk, “chgres” will generate sfc_data, called sfc_data_land;
(1b) slmsk=floor(land_frac) is to take fractional grids as water points. With this slmsk, “chgres” will generate sfc_data, called sfc_data_water.

(2) The two datasets, sfc_data_land and sfc_data_water, are identical except at fractional grids. They are combined in this way:
(2a) “tsea” and “zorl” in “sfc_data_land” are renamed as “tsfcl” and “zorll”,
respectively;
(2b) all variables from “sfc_data_land” are picked to be in the final “sfc_data”, except “fice” and “tisfc”, which are from “sfc_data_water”;
(2c) “tsea” and “zorl” from “sfc_data_water” are picked and added to (3b).

(3) slmsk in the sfc data is modified accordingly in this way:
  if (fice(i) > 0.) then
      slmsk(i)=2
  else
      slmsk(i)=nint(land_frac(i))
  end

The resulting sfc data has 2 new variables: “tsfcl” and “zorll”, compared to the current one. If they don’t exist in sfc_data, FV3 io routine will copy tsea to tsfcl, and zorl to zorll, automatically. 

Let me know if you have any questions or comments. Thanks.

**Comment by HenryWinterbottom-NOAA** [comment]
@shansun6 Does this fix resolve the fractional ocean/land mask that was causing issues for the UFS-S2S (e.g., coupled FV3, MOM6, CICE5) model?

**Comment by shansun6** [comment]
I should have added that this issue is *complementary* to the current
"chgres" by adding 2 new variables in sfc_data, desirable for the
fractional landmask to have a SST and roughness length over land and water,
separately, to start the model with. Currently there is only one
temperature and one roughness length at each grid in sfc_data. FV3 will
still run well with one temperature and roughness, by treating SST and
roughness length the same over land and water at each grid.

Are you talking about the crash with 1deg ocean in UFS-S2S several weeks
ago? That was due to the use of a mismatched oro_data, and has nothing to
do with sfc_data. When an ocean resolution changes, the coastline changes
as well. This will require modifications in the atm oro data to match with
a newly introduced ocean coastline. If one still uses the old oro_data, the
UFS-S2S may crash. For this reason, Denise and I have generated a set of
oro_data for a common combination of different atm and ocean resolutions. I
heard once the new oro_data was used, the model was no longer crashing.
(Obviously, sfc_data needs to be regenerated to be consistent with any new
set of oro_data).

Let me know if you have questions.

Thanks,
Shan

**Comment by HenryWinterbottom-NOAA** [comment]
Yes, I am referring to the crash with the 1-degree ocean. And yes, the new orography files correct the mismatch issue.

Can you point me to a git repo that contains the software to resolve the above-mentioned issue? We may wish to include this as part of the UFS-RNR clone for the UFS-RNR project.

Thank you in advance.

**Comment by shansun6** [comment]
We are working on documenting the process of generating the oro data. It
has been decided in a meeting last week that UFS_UTILS would be the place
to have these scripts committed to. It is a multi-step process
involving multiple parties. I, as well as UFS_UTILS I guess, will let you
know when the final commit is done.

Thanks for your patience,

Shan

**Comment by arunchawla-NOAA** [comment]
@GeorgeGayno-NOAA what would be the ideal process to streamline the process that Shan has laid out above?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA what would be the ideal process to streamline the process that Shan has laid out above?

@arunchawla-NOAA  Sounds like there are two issues here: mismatch issues with the orography data, and updating chgres for fractional grids to include modifying the coldstart files for separate z0 and skin T records for land and non-land.  Are you asking about the latter?  I opened an issue for chgres (#123).  But I have not done any work on it.

**Comment by arunchawla-NOAA** [comment]
The latter yes. Thank you. With the proper initial conditions the mismatch issue should go away

**Comment by GeorgeGayno-NOAA** [comment]
> The latter yes. Thank you. With the proper initial conditions the mismatch issue should go away

If you need the chgres capability quickly, then assign the work to me.  If it not as time critical, then I can provide assistance for what needs to be done.

**Comment by shansun6** [comment]
Hi Arun,

Do you mean with proper "oro data", the mismatch issue should go away?

We have "frozen" a set of oro data with different combinations of atm and
ocean resolutions for the coupled model, and we will run "chgres" based on
these oro data.

Hi George, it would be nice to have "chgres" generate sfc data for the frac
grid in one step. I have generated them manually using a multi-step method
by taking "ceiling" and "floor" of "land_frac", to get temp (and roughness
length) on land and on water, respectively, and then combining them into
one set of sfc data. These data can be used for Prototype 6 in the next 2
months, where the workflow would skip "chgres" step, as the sfc data (from
CFSv2) are available. In the long run, it would be good to have an inline
"chgres" active so there will be more atm ICs options to choose from.

Modifying "chgres" on our own appears to be somewhat challenging. That was
why we avoided it by choosing this multi-step method. If you could
implement it over the next few months, we would be happy to help testing
the output.

Thanks,
Shan

**Comment by GeorgeGayno-NOAA** [comment]
Being worked under #123. Closing
