### ISSUE TITLE
Adding a feature to generate lake fraction in the case of gtype=regional_gfdl

### ISSUE THREAD

**Issue by shansun6** [ufs-community/UFS_UTILS#173]
So far the lake fraction can only be generated for the global domain. We are expanding this capacity to the regional domain called "regional_gfdl".

**Comment by GeorgeGayno-NOAA** [comment]
Note from @shansun6:  lake fraction will be expanded to the ESG regional grid as soon as the SAR group finalizes all domain parameters, as the domain specification will determine how to define the second seed, and potentially the third seed.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 3b0d976.  Closing issue.

**Comment by GeorgeGayno-NOAA** [comment]
> Note from @shansun6: lake fraction will be expanded to the ESG regional grid as soon as the SAR group finalizes all domain parameters, as the domain specification will determine how to define the second seed, and potentially the third seed.

@BenjaminBlake-NOAA - See the note from @shansun6.

**Comment by BenjaminBlake-NOAA** [comment]
@JacobCarley-NOAA @MatthewPyle-NOAA  We want to get this option added for regional_esg_grid so that we can incorporate lake information into the orography files.  Since our domain parameters are finalized we should go ahead and provide those.  I'm guessing we will want to do this primarily for the North American grid?

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Doing for the NA grid makes sense to me.  Does it need a fresh issue, or can someone reopen it?

**Comment by GeorgeGayno-NOAA** [comment]
On second thought, let's close this and open a new issue.

**Comment by ShanSunNOAA** [comment]
Hi -

I think Ning Wang is working on including the ESG grid as a choice for the
regional grid to incorporate lake info into the orography files. He will do
a PR when it is ready.

Thanks,
Shan

**Comment by GeorgeGayno-NOAA** [comment]
@NingWang325 and @shansun6 - Please open an issue to track the updates for the ESG grid. Thanks.
