### ISSUE TITLE
Test UFS_UTILS with combined IP/IP2 library

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [ufs-community/UFS_UTILS#242]
@kgerheiser is combining IP and IP2 into a single library.  Test this library with UFS_UTILS.

https://github.com/NOAA-EMC/NCEPLIBS-ip2/pull/29

**Comment by edwardhartnett** [comment]
Please build a test for this in GitHub actions, so we call all see it. That is, write a test that downloads and builds ip/ip2, then builds and runs UFS_UTILS tests. For an example, see this workflow, which builds a fixed version of pnetcdf, caches it, and then builds PIO with it: https://github.com/NCAR/ParallelIO/blob/master/.github/workflows/cmake.yml

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser I ran the snow2mdl regression test on Hera.  The test ran to completion.  I did not expect bit identical results, but the differences in the snow cover field are larger than they should be.  The cover field is shifted from the baseline.  Snow cover is set from IMS snow data, which uses an elliptical earth.  So my guess is IPLIB is using the wrong radius of the earth or does not realize an elliptical earth was used.  The IMS data is grib1, which sets earth radius in GDS octet 17: https://www.nco.ncep.noaa.gov/pmb/docs/on388/table7.html

**Comment by GeorgeGayno-NOAA** [comment]
General comment: since this is a very big change to the library, should the first digit of the version number be incremented?  i.e., 4.0.0?

**Comment by kgerheiser** [comment]
That's a good lead. I'll take a look there.

> General comment: since this is a very big change to the library, should the first digit of the version number be incremented? i.e., 4.0.0?

Yes, that would be appropriate.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser  Can you create "2d-array", "1d-array" and scalar versions of gdswzd for both grib1 and grib2?  (it looks like scalar grib1 is missing).  I call gdswzd with scalars for grib1 in my snow program.  To get it to compile, I have to call 'gdswzd_grib1'.   For the non-scalar calls, I am able to call the gdswzd interface directly.

**Comment by kgerheiser** [comment]
I think I found the problem. You were right about the earth radius. I wasn't setting the WGS-84 radius when it was an elliptical Earth.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser My branch won't compile anymore. You test library was here: /home/Kyle.Gerheiser/NCEPLIBS-ip2.

**Comment by kgerheiser** [comment]
Oh, I deleted that yesterday.

**Comment by kgerheiser** [comment]
`grid_gen`, `snow2mdl`, and `global_cycle` tests pass

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser Has IP v4 been installed on any of our machines? This issue has been open for a while.

**Comment by GeorgeGayno-NOAA** [comment]
@Hang-Lei-NOAA Has IP v4 been installed on any of our machines?

**Comment by Hang-Lei-NOAA** [comment]
No, I can install it on Hera tonight.

**Comment by Hang-Lei-NOAA** [comment]
It has been added on Hera.

**Comment by GeorgeGayno-NOAA** [comment]
To ease the transition between IP library v3.3.3 and v4.0, the rank of some arrays were changed to comply with the `gdswzd` and `ipolates` routine interface changes.  Therefore, the regression tests have to be rerun using both v3.3.3 and v4.0.

First, I tested the branch at 59292b4 using IP library v3.3.3 (on Cactus). The `snow2mdl`, `global_cycle` and `grid_gen` regression tests all passed as expected.

**Comment by GeorgeGayno-NOAA** [comment]
> To ease the transition between IP library v3.3.3 and v4.0, the rank of some arrays were changed to comply with the `gdswzd` and `ipolates` routine interface changes. Therefore, the regression tests have to be rerun using both v3.3.3 and v4.0.
> 
> First, I tested the branch at [59292b4](https://github.com/ufs-community/UFS_UTILS/commit/59292b446ae8b4a7fe829f0021866f1e38a21577) using IP library v3.3.3 (on Cactus). The `snow2mdl`, `global_cycle` and `grid_gen` regression tests all passed as expected.

Repeated this test on Hera. All tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
Note: To compile with v4.0, you need to uncomment the `use ipolates_mod` statement in `./sorc/emcsfc_snow2mdl.fd/snow2mdl.F90` and in `./orog.fd/mtnlm7_oclsm.f` and adjust the build modules.

**Comment by edwardhartnett** [comment]
George, I have found it best to make changes so that both versions are handled.

That is, I check in the CMake file what version I am dealing with, and then use ifdefs in the code to handle both versions of the code.

Does this make sense?

Technically we could just say ip-4.0.0 is required and users should just deal with it, but it is kinder not to make it mandatory if we don't have to...

**Comment by GeorgeGayno-NOAA** [comment]
> George, I have found it best to make changes so that both versions are handled.
> 
> That is, I check in the CMake file what version I am dealing with, and then use ifdefs in the code to handle both versions of the code.
> 
> Does this make sense?
> 
> Technically we could just say ip-4.0.0 is required and users should just deal with it, but it is kinder not to make it mandatory if we don't have to...

That would be great. Do you have a CMake example I can look at?

**Comment by edwardhartnett** [comment]
I have not done it for ip, but if you look at g2 you will see it can handle two very different versions of bacio...

**Comment by GeorgeGayno-NOAA** [comment]
> It has been added on Hera. On Wed, Sep 7, 2022 at 2:44 PM Hang Lei - NOAA Affiliate ***@***.***> wrote:


@Hang-Lei-NOAA Can you also install the GNU version on Hera?

**Comment by Hang-Lei-NOAA** [comment]
@George Gayno - NOAA Affiliate ***@***.***> I have added it
under the GNU compiler option.

**Comment by GeorgeGayno-NOAA** [comment]
@Hang-Lei-NOAA Thanks for installing on Hera. Please install on Orion and Jet when you are not busy. And add it to your next NCEPLIBS upgrade on WCOSS2.

**Comment by GeorgeGayno-NOAA** [comment]
Commit 794304d was compiled on Orion. All consistency tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
Tested Hang's ip v4.0 on Cactus. Using 5fbfa1f, the `chgres_cube`, `global_cycle`, `grid_gen` and `snow2mdl` consistency tests all passed.
