### ISSUE TITLE
Split input_data.F90 into `atm_input_data`, `sfc_input_data`, and `nst_target_data`

### ISSUE THREAD

**Issue by kgerheiser** [ufs-community/UFS_UTILS#460]
`input_data.F90` is a really long file that I think could be broken up to make it more managable. It seems like it does 3 different things for 3 types of data, and it would make sense to group them together.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser This will make writing unit tests easier. What is the status? I can work on this if you are busy with other tasks.

**Comment by kgerheiser** [comment]
I'll put in a PR today.

**Comment by LarissaReames** [comment]
@kgerheiser did you ever go back to try to tackle this? I think it's still worth doing as that file really is quite large.

**Comment by GeorgeGayno-NOAA** [comment]
> @kgerheiser did you ever go back to try to tackle this? I think it's still worth doing as that file really is quite large.

Unfortunately, Kyle no longer works for NOAA. But I still think his suggestion is a good one.

**Comment by LarissaReames** [comment]
> > @kgerheiser did you ever go back to try to tackle this? I think it's still worth doing as that file really is quite large.
> 
> Unfortunately, Kyle no longer works for NOAA. But I still think his suggestion is a good one.

Yes I think so too. Any thoughts on the best way to do this? Do we just do a straight up split of those subroutines in to 3 files?

**Comment by GeorgeGayno-NOAA** [comment]
> > > @kgerheiser did you ever go back to try to tackle this? I think it's still worth doing as that file really is quite large.
> > 
> > 
> > Unfortunately, Kyle no longer works for NOAA. But I still think his suggestion is a good one.
> 
> Yes I think so too. Any thoughts on the best way to do this? Do we just do a straight up split of those subroutines in to 3 files?

Maybe the first step is to do an inventory of all the routines and what they do. Not all of the routines read data. Some could probably be moved to the utility module.
