### ISSUE TITLE
Put rest of chgres_cube code into modules

### ISSUE THREAD

**Issue by kgerheiser** [ufs-community/UFS_UTILS#461]
`utils.F90` and `write_data.F90` don't use modules. It's good for all code to be in modules for explicit type-checking of functions.

**Comment by GeorgeGayno-NOAA** [comment]
write_data.F90 was placed in a module under this PR - #631

**Comment by LarissaReames** [comment]
@kgerheiser Are there any other thoughts for parts of the code that could be split into separate modules?

**Comment by GeorgeGayno-NOAA** [comment]
`utils.F90` and `write_data.F90` are now modules. Closing.
