### ISSUE TITLE
chgres_cube:  output in restart format when input from warm start files

### ISSUE THREAD

**Issue by ZhanZhang-NOAA** [ufs-community/UFS_UTILS#520]
Current version of chgres_cube is able to take a FV3 warm restart file and interpolate/remap it to a different resolution/domain-coverage in cold-start format, but not in fv3 warm restart format.

Is it possible to enhance the current chgres_cube capability to write output file in warm restart format when input from warm start file. This capability will be very useful for conversions, fields remapping between different domain coverages and resolutions, which are needed in HAFS and other UFS applications.

**Comment by GeorgeGayno-NOAA** [comment]
@ZhanZhang-NOAA To whom should I assign this task?

**Comment by GeorgeGayno-NOAA** [comment]
Initial scope of work:

- New routines to output data in the warm restart format. Like the cold start files, the warm start files are NetCDF.  However, unlike the cold start format, the warm restart atmospheric data is stored in multiple files.
- In the cold start files, the u/v winds are on the 'a' grid and earth relative. In the warm restart files, they are staggered and tile relative. So routines to turn the winds to the tile will need to be identified and added to chgres.

**Comment by GeorgeGayno-NOAA** [comment]
Some notes about the surface files: The cold and warm restart files contain most of the same fields, with the same record id and the same units. That is a good thing. But there are some differences:

- The cold start files contain 'geolat' and 'geolon' records. Those records are not in the warm start files.
- The 'zm' field is zeroed out in the cold start files. It contains real data in the warm start files.
- The warm start files have a snow cover record ('sncovr') that is not in the cold start file.
- The 'srflag' (snow/rain flag) record is zeroed out in the cold start files. It contains real data in the warm start files.
- The 'ffhh' record is zeroed out in the cold start files. It contains real data in the warm start files.

**Comment by GeorgeGayno-NOAA** [comment]
@HelinWei-NOAA How is snow cover computed by the LSM? Which routine?

**Comment by HelinWei-NOAA** [comment]
> @HelinWei-NOAA How is snow cover computed by the LSM? Which routine?

snow cover is computed differently in three different LSMs inside UFS. However the Noah LSM routine is used to initialize the snow cover inGFS_phys_time_vary.fv3.F90:

!$OMP section
         !--- if sncovr does not exist in the restart, need to create it
         if (all(sncovr < zero)) then
           if (me == master ) write(0,'(a)') 'GFS_phys_time_vary_init: compute sncovr from weasd and soil vegetation parameters'
           !--- compute sncovr from existing variables
           !--- code taken directly from read_fix.f
           sncovr(:) = zero
           do ix=1,im
             if (landfrac(ix) >= drythresh .or. fice(ix) >= min_seaice) then
               vegtyp = vtype(ix)
               if (vegtyp == 0) vegtyp = 7
               rsnow  = 0.001_kind_phys*weasd(ix)/snupx(vegtyp)
               if (0.001_kind_phys*weasd(ix) < snupx(vegtyp)) then
                 sncovr(ix) = one - (exp(-salp_data*rsnow) - rsnow*exp(-salp_data))
               else
                 sncovr(ix) = one
               endif
             endif
           enddo
         endif

This is corresponding to the subroutine snfrac inside sflx.f (Noah LSM)

**Comment by GeorgeGayno-NOAA** [comment]
@junwang-noaa I have questions about starting the model with warm restart files. For example, are all records in the restart files actually needed or are some diagnostic? Who would I ask? Which model routine reads the restart files?

**Comment by junwang-noaa** [comment]
George, There are some diagnostic fields in the restart files (e.g. non
bucket total avg precip and total ave convective precip) in restart
phy_data in order to get restart reproducibility. The code to read restart
files are: in dycore, subroutine fv_io_read_restart in
FV3/atmos_cubed_sphere/tools/fv_io.F90 and subroutine
sfc_prop_restart_read and phys_restart_read in FV3/io/FV3GFS_io.F90 for
physics restart files .

**Comment by GeorgeGayno-NOAA** [comment]
> George, There are some diagnostic fields in the restart files (e.g. non bucket total avg precip and total ave convective precip) in restart phy_data in order to get restart reproducibility. The code to read restart files are: in dycore, subroutine fv_io_read_restart in FV3/atmos_cubed_sphere/tools/fv_io.F90 and subroutine sfc_prop_restart_read and phys_restart_read in FV3/io/FV3GFS_io.F90 for physics restart files .


https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/3720aeae54eeed54d4e8274756857542b3e5dccc/tools/fv_io.F90#L145

**Comment by BinLiu-NOAA** [comment]
@GeorgeGayno-NOAA, is it ok that I point you to the regional FV3 restart files for you to look at or test with? Or you would prefer to start with global model (saying GFSv16) restart files to start with? For GFSv16 (GFS/GDAS) restart files, I can point you to the wcoss operational location. For regional restart files, I can create/point you to the corresponding files on Orion (or other platforms).

Thanks!

Bin

**Comment by GeorgeGayno-NOAA** [comment]
Code to turn the winds from earth relative to grid relative (when reading coldstart files):

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/3720aeae54eeed54d4e8274756857542b3e5dccc/tools/external_ic.F90#L735

**Comment by BinLiu-NOAA** [comment]
@GeorgeGayno-NOAA, when choosing to write out the warm start files with your feature/warm_start branch, is there a restriction that the input data have to be restart files? Or the input can also be GFS/GDAS netcdf/grib2 files? Thanks!
