### ISSUE TITLE
Reconfigure testing directory structure

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/UFS_UTILS#535]
Based on recent changes to the testing infrastructure for UFS_UTILS, I would propose rearranging directories as follows:

1) Move the current sub-directories in "tests" into a directory called "unit_tests"
2) Rename "reg_tests" to "consistency_tests" and place it in the "tests" directory

**Comment by edwardhartnett** [comment]
Unit tests should be in a directory call "tests" to conform to CMake conventions.

I have no objection to renaming or moving the reg_tests directory, if that seems helpful. But is it?

**Comment by JeffBeck-NOAA** [comment]
I think having a "tests" directory with sub-directories called "unit_tests" and "consistency_tests" makes sense.
