### ISSUE TITLE
Add code to ingest snow increments from JEDI for the Noah-MP model 

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [ufs-community/UFS_UTILS#562]
This issue follows from #561, but is now for Noah-MP not Noah. 

Noah-MP has a multilayer snow model, and the code to add the increments is more involved. Also, we will not be able to separate out the steps into: 1) update snow depth, 2) adjust other variables, as is done for Noah. I suggest we skip the first step, and use the current code structure (calling code from lsm_routines) to apply the update.

Mike B will do this once Clara has done #561.

**Comment by GeorgeGayno-NOAA** [comment]
@barlage There has not been much activity on this issue. Should I keep it open?

**Comment by ClaraDraper-NOAA** [comment]
I'm doing this outside of UFS_UTILS, as I needed to be able to handle fractional grid cells. However, Jiarui is now integrating my work into EMC's GDAS system, so we should think about how we want to do this. I suggest Mike and I discuss this at our tag-up on Tuesday. 

@GeorgeGayno-NOAA Can UFS_UTILS manage fractional grid cells yet?

**Comment by GeorgeGayno-NOAA** [comment]
> I'm doing this outside of UFS_UTILS, as I needed to be able to handle fractional grid cells. However, Jiarui is now integrating my work into EMC's GDAS system, so we should think about how we want to do this. I suggest Mike and I discuss this at our tag-up on Tuesday.
> 
> @GeorgeGayno-NOAA Can UFS_UTILS manage fractional grid cells yet?

Not yet.

**Comment by ClaraDraper-NOAA** [comment]
Thanks @GeorgeGayno-NOAA. We'll get back to you next week.

**Comment by ClaraDraper-NOAA** [comment]
@GeorgeGayno-NOAA  Mike and I just had a quick chat about this, and decided to continue doing the Noah-MP snow depth updates outside of UFS_UTILS, so yes, you can close this.

FYI: This is the code currently being used: 
https://github.com/NOAA-PSL/land-apply_jedi_incr.git

Long-term we could bring this back into UFS_UTILS once the latter can handle Noah-MP and fractional grids, if this seems appropriate.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Mike and I just had a quick chat about this, and decided to continue doing the Noah-MP snow depth updates outside of UFS_UTILS, so yes, you can close this.
> 
> FYI: This is the code currently being used: https://github.com/NOAA-PSL/land-apply_jedi_incr.git
> 
> Long-term we could bring this back into UFS_UTILS once the latter can handle Noah-MP and fractional grids, if this seems appropriate.

Ok. Thanks for the update.
